apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: block-rbac
  namespace: argocd
spec:
  project: product-team
  source:
    repoURL: https://github.com/dag-andersen/argocon-eu-2025-code.git
    path: test-apps/rbac-creation
    targetRevision: test-branch
  destination:
    name: in-cluster
    namespace: argocd
