apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: innocent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/repo.git
    path: apps/innocent-app
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
