apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-everything
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-everything
subjects:
  - kind: ServiceAccount
    name: list-resources-sa  # Name of the ServiceAccount
    namespace: default       # Namespace where the ServiceAccount is created
roleRef:
  kind: ClusterRole
  name: allow-everything
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allow-everything
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: my-malicious-pod
  namespace: default
spec:
  serviceAccountName: allow-everything
  containers:
    - name: test-container
      image: hacker-city/hack-image
      command: ["sh", "-c", "echo 'I am in!' && sleep 3600"]