apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  ...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a
  namespace: argocd
spec:
  ...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: innocent-app
  namespace: argocd
spec:
  ...
---