apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-creator-binding
  namespace: guestbook-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-creator
subjects:
- kind: ServiceAccount
  name: guestbook-deployer
  namespace: guestbook-dev
