apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
spec:
  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:team-a:read-only, applications, get, team-a/*, allow
    - p, proj:team-a:read-only, logs, get, team-a/app-1, deny
  - description: Delete Pods
    name: delete-pods   
    policies:
    - p, proj:team-a:delete-pods, applications, delete/*/Pod/*/*, team-a/app-1, allow
    - p, proj:team-a:read-only, applications, get, team-a/*, allow
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'

