apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
spec:
  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:team-a:read-only, applications, get, team-a/*, allow
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
