apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceBlacklist:
  # Block the creation of RBAC resources
  - group: 'rbac.authorization.k8s.io'
    kind: Role
  - group: 'rbac.authorization.k8s.io'
    kind: RoleBinding
  # Block the creation of MutatingWebhookConfiguration
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration
  # Block the creation of AppProject and Application
  - group: 'argoproj.io'
    kind: Application
  - group: 'argoproj.io'
    kind: AppProject
  clusterResourceBlacklist:
  # Block the creation of RBAC resources
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  sourceRepos:
    # only allow apps from your org
    - https://github.com/<org>/*
  destinations:
  # Do not allow any app to be installed in `kube-system`  
  - namespace: '!kube-system'
    server: '*'
  # Do not allow any app to be installed in `argocd`
  - namespace: '!argocd'
    server: '*'
  # Do not allow any app to be installed in `argocd`
  - namespace: '!database-proxy'
    server: '*'
  # Whitelist the rest
  - namespace: '*'
    server: '*'
---